# 数据库信息配置
#         host="127.0.0.1",
#        port=3306,
#        database="sys",
#        charset="utf8",
#        user="root",
#        passwd="123456"
user: 'root'
password: '123456'
host: '127.0.0.1'
port: 3306
database: 'sys'

